### ISSUE TITLE
Message cut into two boxes

### ISSUE THREAD

**Issue by brunolramaral** [push-platform/push-webchat#28]
![Anotação 2020-07-14 190450](https://user-images.githubusercontent.com/18313641/87481064-f91fc880-c604-11ea-9b70-e69b6316b14f.png)

**Comment by paulobernardoaf** [comment]
@brunolramaral Could you provide a `.html` file that can replicate this issue, please?

**Comment by brunolramaral** [comment]
The problem was in a platform configuration! Solved!!!
